export const ExerciseSeed = [
  {
    name: '스쿼트',
    priority: 1,
    part: 'LOWER',
    baseCount: 15,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what: 'Squat는 쪼그리고 앉다는 뜻으로 데드리프트, 벤치프레스와 더불어 웨이트 트레이닝의 3대 운동 중 하나입니다.\n특히 하체 운동에서는 절대 빠지면 안 되는 운동입니다.\n바벨 또는 덤벨을 들고 혹은 맨몸으로 무릎 관절을 굽혀다 펴는 행동을 반복함으로써 하반신의 근육을 성장시키는 운동입니다.',
      where: '대퇴사두근, 둔근, 척주기립근, 복부 근육, 대퇴근 후면 근육이 집중적으로 운동됩니다.\n위 근육들이 스쿼트 자극 부위라고 생각하고 운동해 주셔야 합니다.',
      how: [
        '앉았다 일어나는 동작을 기본으로 하는데 어깨너비로 발을 벌리고 서서 발가락이 전면을 향하도록 선 후, 허리는 곧게 펴고, 상체도 최대한 꼿꼿하게 펴는 것이 좋습니다.',
        '무릎의 위치를 신경 쓰기보다는 의자에 앉는다는 느낌으로 자연스럽게 엉덩이를 낮추면 됩니다.\n개인마다 신체 비율이 다르기 때문에 스쿼트를 처음 시작할 때는 누군가 봐주거나 거울을 통해 자신의 모습을 지켜보는 것이 좋습니다.',
        '스쿼트에서 가장 중요한 것은 엉덩이를 낮췄다가 일어나는 동작에서 반동으로 움직이는 것이 아니라 복부와 엉덩이의 힘으로 일어나야 합니다.\n반동을 주며 횟수를 많이 하는 것은 운동 효과에 도움이 되지 않으며, 천천히 바른 자세로 제대로 하는 것이 중요합니다.',
      ],
      caution: '스쿼트는 분명히 프리 웨이트 중에서 최고의 운동효과를 낼 수 있는 운동입니다.\n하지만 최고의 프리 웨이트답게 생각보다 높은 난이도를 자랑하는 운동입니다.\n지도자들이나 트레이너들도 조금 더 깊이 있게 들어가면 스쿼트에 관해서 쩔쩔매는 것이 사실입니다.\n또한 인터넷이나 책으로만 접하거나 제대로 된 교육을 받지 않은 많은 사람들이 잘못된 자세로 스쿼트를 시행하는 경우를 볼 수 있습니다.\n잘못된 자세로 시행되는 스쿼트는 무릎-허리와 같은 회복 불가능의 퇴행성 질환을 유발하며 어깨와 손목에도 심각한 부상을 유발하기도 합니다.\n무조건 달려가서 무거운 중량으로 하기보다는 반드시 정확한 자세를 습득 후에 시행하기 바랍니다.',
    }),
    imageLink: 'https://gif.helltabus.com/17601301/17601301-Dumbbell-Goblet-Squat_Thighs-FIX_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '런지',
    priority: 2,
    part: 'LOWER',
    baseCount: 15,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03361301/03361301-Dumbbell-Lunge_Hips_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레그 프레스',
    priority: 3,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/07391301/07391301-Sled-45-370-Leg-Press_Hips_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '라잉 레그 컬',
    priority: 4,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/05861301/05861301-Lever-Lying-Leg-Curl_Thighs_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레그익스텐션',
    priority: 5,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/05851301/05851301-Lever-Leg-Extension_Thighs_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 벤트 오버 로우',
    priority: 1,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/02931301/02931301-Dumbbell-Bent-Over-Row_Back-FIX_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 암 풀오버',
    priority: 2,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 4,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/04331301/04331301-Dumbbell-Straight-Arm-Pullover_Chest-FIX_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '렛풀다운',
    priority: 3,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/01971301/01971301-Cable-Pulldown-(pro-lat-bar)_Back_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '시티드로우',
    priority: 4,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/02391301/02391301-Cable-Straight-Back-Seated-Row_Back_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '백익스텐션',
    priority: 5,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/08771301/08771301-45-degree-hyperextension-(arms-in-front-of-chest)_Back_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 벤치프레스',
    priority: 1,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'스쿼트, 데드리프트와 함께 웨이트 트레이닝을 대표하는 3대 운동 중 하나입니다. 덤벨 벤치 프레스는 비록 바벨만큼 고중량을 들기에는 어렵지만 범용성이라는 큰 장점이 있습니다. 양손의 가동범위가 자유로운만큼 운동 반경이나 손의 회전 등 운동 동작의 변형을 통해 좀 더 다양한 자극을 줄 수도 있고, 또 자신의 신체에 좀 더 적합한 동작으로 운동을 수행해낼 수도 있습니다.',
      where:'대흉근 전체 가동 범위에서 동작이 이루어지기 때문에 가슴을 모아주는 중앙 부위와 바깥쪽 근육의 크기를 키우는 데 효과적입니다.',
      how:[
        '벤치에 앉아 팔을 가슴 옆에 붙이고 덤벨을 듭니다.',
        '벤치에 누워 가슴 중앙 부분과 수직이 되게 덤벨을 위치시키면서 팔꿈치를 살짝 구부립니다.',
        '가슴이 양옆으로 늘어나는 느낌을 느끼면서 덤벨이 가슴과 평행이 될 때까지 당깁니다.',
        '겨드랑이에 힘을 주면서 가슴을 모아주는 느낌으로 덤벨을 밀어 올립니다.'
      ],
      caution:'덤벨을 내리면서 어깨가 등 뒤로 과도하게 젖혀지면 어깨 주변 근육의 부상 위험이 커질 수 있습니다.\n벤치에 누울 때는 엉덩이, 허리, 등, 어깨가 순서대로 닿을 수 있도록 합니다.'
    }),
    imageLink: 'https://gif.helltabus.com/02891301/02891301-Dumbbell-Bench-Press_Chest_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  }, {
    name: '덤벨 플라이',
    priority: 2,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'몸 위쪽으로 날갯짓 하듯 반원을 그리며 가슴을 모으는 동작입니다. 덤벨 플라이의 기본은 평평한 플랫 벤치이지만, 인클라인 벤치나 디클라인 벤치를 활용하면 가슴 부위 자극에 다양성을 부여하여 근육 발달의 완성도를 조금 더 높일 수 있습니다.',
      where:'왼쪽과 오른쪽 가슴이 만나는 중앙 부분을 발달시키는 운동으로, 가슴 중앙 부위의 섬세한 근육 분리와 함께 가슴을 예쁘게 모아 주는 운동입니다.',
      how:[
        '손바닥이 서로 마주보게 덤벨을 잡아 허벅지에 올려놓습니다.',
        '벤치에 누워 가슴 앞쪽으로 양 팔을 앞으로 나란하게 뻗습니다.',
        '팔꿈치를 자연스럽게 구부리며 가슴 옆 방향으로 천천히 펼쳐 줍니다. 이 때, 가슴이 완전히 스트레칭 되는 벤치 높이까지 팔꿈치가 도달하도록 당겨주셔야합니다.',
        '호흡을 내쉬며 날개짓하듯 반원을 그리며 덤벨을 모읍니다. 가동 범위를 충분히 활용하기 위해, 덤벨을 부딪혀 깡 소리가 나도 좋습니다.',
        '동작의 정점에서 가슴 근육을 강하게 한번 짜 준 후 호흡을 들이쉬며 2~3번 과정을 다시 반복합니다.'
      ],
      caution:'덤벨을 내릴 때 팔꿈치를 완전히 펴면 동작이 부자연스러워 지고, 팔꿈치를 너무 많이 굽히면 충분한 스트레칭 효과를 얻기 어려우므로 밋밋한 곡선이 이루어지게끔 살짝만 구부리셔야합니다. 어깨에 통증이 일어나지 않는 범위하에서 가동범위를 충분히 활용하셔야합니다. 각도 조절이 가능한 벤치일 경우 1칸씩 미세하게 변화를 주어 운동한다면 변화된 각도에 따라 조금씩 다른 근섬유가 개입되어 가슴부위의 발달을 극대화하는데 도움이 될 것입니다. 이러한 방법을 덤벨 플라이 뿐만 아니라 다른 가슴운동들에 까지 확대해 나간다면 가슴근육의 최대발달을 이룰 수 있을 것입니다.'
    }),
    imageLink: 'https://gif.helltabus.com/03081301/03081301-Dumbbell-Fly_Chest-FIX_1080.gif',

    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 인크라인 벤치프레스',
    priority: 3,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'덤벨을 이용한 가슴상부 운동으로 폭이 좁은 벤치에 드러누워 역기를 두 팔로 떠받치고 가슴 위에서 올렸다 내렸다 하는 웨이트 트레이닝입니다.',
      where:'대흉근을 발달시키는 운동입니다. 수축과 이완 시 덤벨의 균형을 잘 잡아야 하므로 균형감각을 키울 수 있고 가슴을 예쁘고 탄력 있게 만들 수 있습니다.',
      how:[
        '벤치의 각도는 45도로 높여주고 덤벨을 잡은뒤 벤치에 누워줍니다.',
        '덤벨을 귀옆으로 붙이고 쇄골과 덤벨이 수직이 되게 만들어 줍니다.',
        '팔꿈치를 굽혀 서서히 겨드랑이에 힘을주어 밀어올려줍니다.',
        '자극점을 유지하며 운동은 진행합니다.'
      ],
      caution:'팔꿈치가 뒤쪽으로 쳐진다거나 움직이면 안됩니다. 바로 고정된 상태에서 가슴 자극만 주는것이 효과적인데 축이 무너져 흔들리게되면 운동효과가 전혀 없는 것은 물론 부상의 위험도 높을수있으니 이런 경우가 생긴다면 중량을 낮춰 윗가슴 운동을 수행해주세요.'
    }),
    imageLink: 'https://gif.helltabus.com/03141301/03141301-Dumbbell-Incline-Bench-Press_Chest_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 체스트 프레스',
    priority: 4,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'레버 체스트 프레스는 가슴 근육 주변을 운동하여 가슴 라인을 이쁘게 잡아주는 기본적인 가슴 운동입니다.',
      where:'대 흉근(가슴), 삼각근(어깨), 상완 삼두근(팔 뒷 부분), 주근(상완근)이 운동됩니다.',
      how:[
        '벤치에 엉덩이, 윗 등을 붙이고 가슴을 최대한 오픈시켜줍니다.',
        '가슴에 힘을 주면서 앞으로 밀어줍니다. 이때, 사전에 손잡이가 가슴 정중앙에 위치할 수 있게 벤치 높이를 조절해 줍니다.',
        '손목, 팔꿈치를 일직선으로 유지시킨 상태에서 팔꿈치를 뒤로 천천히 빼줍니다. (이때 가슴근육이 땡기는 느낌을 받아야 합니다.)',
        '다시 가슴에 힘을 주면서 밀어줍니다.'
      ],
      caution:'팔꿈치가 어깨와 일직선이거나 어깨 위로 올라가면 안됩니다. 팔꿈치가 위로 올라가면 어깨에 힘이 많이 들어가게 됩니다.\n팔꿈치가 손목보다 너무 밑에 있으면 안됩니다. 팔꿈치가 손목보다 너무 밑에 있으면 팔에 힘이 많이 들어가게 됩니다.\n프레스 했을 때 어깨가 앞으로 나오면 안됩니다.'
    }),
    imageLink: 'https://gif.helltabus.com/05771301/05771301-Lever-Chest-Press_Chest_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 시티드 플라이',
    priority: 5,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'가슴근육의 모양을 다듬고, 가슴 안쪽부분을 발달시켜줍니다. 가슴 안쪽 근육으로 조이고 모으면서 양손의 간격을 좁혀주며 껴안듯이 날개짓 하며 안으로 모아줍니다.',
      where:'대흉근 전면 전체적으로 운동이 됩니다.',
      how:[
        '양 손잡이가 어깨 보다 앞으로 나오게 위치 조정한다. 손잡이가 가슴 중상부에 오도록 의자 위치를 조정합니다.',
        '견갑골과 엉덩이를 등받이에 최대한 붙이고 허리는 아치형을 만듭니다.',
        '팔꿈치를 살짝 구부리고 손잡이는 가슴 중앙과 수평이 되도록합니다.',
        '겨드랑이에 힘을 주고 손잡이를 가슴 앞으로 모아줍니다. 팔로 미는 것이 아니라 팔꿈치로 모은다는 느낌으로 동작을 실시합니다.',
        '수축 지점에서 대흉근의 긴장을 유지한 상태에서 1~2초 버팁니다.',
        '이완시 숨을 들이쉬면서 가슴을 내밀어 대흉근의 최대 이완이 이루어지도록합니다. 저항을 느끼면서 시작 자세로 돌아옵니다. 시작 자세로 돌아온 후에도 대흉근에 힘을 빼지 않고 긴장한 상태를 유지해야합니다.',
        '동작을 반복합니다.'
      ],
      caution:'손이나 팔에 힘을 빼고 팔이 아니라 팔꿈치로 밀듯이 동작을 행합니다.\n팔을 너무 올리거나 무게가 너무 많으면 어깨 주변 근육에 상해를 입을 수 있으므로 중량 선택 시 가급적 가벼운 중량을 하도록 합니다.\n어깨가 올라가지 않게 주의합니다.\n운동 시 팔꿈치 각도를 90도 이하로 굽히지 않습니다.'
    }),
    imageLink: 'https://gif.helltabus.com/05961301/05961301-Lever-Seated-Fly_Chest_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레터럴 레이즈',
    priority: 1,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'레터럴 레이즈는 양손에 덤벨을 옆으로 들어 올리는 운동입니다.',
      where:'팔을 들어 올리게 해줄 때 느껴지는 근육인 측면 삼각근을 기르는 운동입니다. 측면 삼각근의 볼륨감을 살려주고, 전면과 후면 삼각근을 자연스럽게 이어주는 역할을 합니다.',
      how:[
        '덤벨을 양손으로 잡은 뒤 어깨 양옆으로 벌리면서 동작합니다.',
        '자세는 어깨 간격으로 다리를 벌려 선 후, 몸을 곧게 펴고 반동이 일어나지 않도록 몸을 고정합니다.',
        '덤벨을 쥘 때는 손등이 앞을 보이도록 그립을 하는 것이 적합하고 팔꿈치와 손목이 아닌 삼각근의 힘을 이용합니다.'
      ],
      caution:'지나치게 넓은 가동 범위는 어꺠에 무리를 줄 수 있습니다.\n어깨 들석임을 포함한 반동을 이용하지 않아야 합니다.\n등과 허리가 구부러지면, 운동효과가 반감될 수 있습니다.'
    }),
    imageLink: 'https://gif.helltabus.com/03341301/03341301-Dumbbell-Lateral-Raise_shoulder-AFIX_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '프론트 레이즈',
    priority: 2,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'프론트 레이즈는 덤벨을 바깥, 정면으로 들면서 어깨를 단련시키는 운동입니다.',
      where:'프론트 레이즈는 덤벨을 정면으로 들어올리는 운동이므로 이 운동은 특히 전면 삼각근 발달에 탁월합니다. 근력운동의 일종이다보니 근육의 크기를 높이는 데에도 물론 도움이 되지만, 그보다는 근육의 모양을 세밀하게 다듬을 때 효과가 있습니다.',
      how:[
        '다리를 어깨넓이 11자로 자연스럽게 섭니다.',
        '팔꿈치를 아주 살짝 구부려주시고, 손의 위치를 허벅지 앞 쪽에 둡니다.',
        '어깨에서 팔꿈치까지 힘을 주어 팔을 앞으로 올립니다.',
        '팔을 올릴 때 호흡을 내쉬고, 팔을 내릴 때 호흡을 들이마시면 됩니다.'
      ],
      caution:'어깨가 부상을 당하지 않게 주의해야 합니다. 어깨는 생각하는 것보다 더 쉽게 자극을 받고 손상을 입기 때문에 지나치게 무겁거나 가동 범위의 한계를 벗어나지 않게 주의하셔야합니다.'
    }),
    imageLink: 'https://gif.helltabus.com/03101301/03101301-Dumbbell-Front-Raise_Shoulders_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '리어 레터럴 레이즈',
    priority: 3,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'레터럴 레이즈 동작을 상세를 숙여준 자세에서 시행하는 운동입니다. 상체를 숙이고 동작을 하기 때문에 다리의 반동을 줄일 수 있을 뿐만 아니라 어깨 근육만 사용하여 좀 더 집중해 운동을 할 수 있다는 장점이 있습니다.',
      where:'등상부, 등 중심부, 측면과 후면삼각근이 운동됩니다.',
      how:[
        '양손에 덤벨을 들고 몸통이 바닥과 거의 수평이 될때까지 상체를 앞으로 기울입니다.',
        '어깨로부터 덤밸을 아래로 곧게 내리고 손바닥이 마주보게 그립을 잡습니다.',
        '어깨로부터 덤밸을 아래로 곧게 내리고 손바닥이 마주보게 그립을 잡습니다.',
        '최고지점에서 잠시 멈춘 후 시작 자세로 천천히 돌아갑니다.'
      ],
      caution:'등을 곧게 유지합니다.\n몸통이 흔들리지 않게 합니다. (반동을 주지 않습니다.)\n처음부터 너무 무거운 무게로 운동하지 않습니다.'
    }),
    imageLink: 'https://gif.helltabus.com/03801301/03801301-Dumbbell-Rear-Lateral-Raise_Shoulders_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '아놀드 프레스',
    priority: 4,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'아놀드 프레스는 숄더 프레스(오베헤드 프레스)을 변형한 동작입니다. 앉아서도, 서서도 할 수 있습니다.',
      where:'운동의 가동 범위가 길어 전면, 측면 삼각근의 모든 부분을 자극합니다. 삼각근이 많이 늘어난 상태에서 수축하는 동작이기에 난이도가 높아집니다.',
      how:[
        '운동의 가동 범위가 길어 전면, 측면 삼각근의 모든 부분을 자극합니다. 삼각근이 많이 늘어난 상태에서 수축하는 동작이기에 난이도가 높아집니다.',
        '그 상태 그대로 팔을 열고 손바닥은 정면을 보게 합니다. 승모근이 올라가지 않도록 주의하는 것이 좋습니다.',
        '덤벨을 위쪽으로 뻗습니다. 올렸을 때 덤벨은 서로 닿지 않아야 하고, 팔꿈치를 완전히 펴지 않아야 합니다.',
        '역순으로 천천히 내립니다.'
      ],
      caution:'동작 내내 허리가 꺾이지 않고, 몸통이 움직이지 않도록 코어를 잘 잡아야 합니다. 내려올 땐 동작을 천천히 통제하며 내려와야 합니다. 한 팔씩 교대로 운동해도 좋습니다.\n모든 어깨 운동에서 과한 무게를 주의해야 하지만, 다른 어떤 운동보다도 가벼운 무게로 시작해야 하는 운동입니다.\n어깨 관절이 불안정한 사람에게는 좋은 운동이 아닐 수 있습니다.'
    }),
    imageLink: 'https://gif.helltabus.com/21371301/21371301-Dumbbell-Arnold-Press_Shoulders_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 숄더 프레스',
    priority: 5,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'숄더(shoulder)는 어깨를 뜻하므로 숄더 프레스란 어깨의 근육을 이용해 미는(press)운동입니다.\n어깨 주변의 근육은 상당히 많지만 주로 회전근개에 관심이 있는 정형외과 영역과는 달리 저항운동에서는 어깨외측에서 가장 튀어나와 있어서 옆선을 결정짓는 삼각형 모양의 근육인 삼각근(deltoid muscle)이 주된 관심사이며 지금 소개하는 숄더프레스도 삼각근의 트레이닝을 위한 운동입니다. 앞쪽, 외측, 뒷쪽 이렇게 3부분으로 구성되어 있고 작용또한 틀려서 각각 팔을 앞으로(굴곡), 옆으로(외전), 뒤로(신전) 들어올리는 역할을 합니다.',
      where:'숄더 프레스를 통해 단련되는 근육은 일차적으로는 삼각근 중에서도 앞쪽 부분이며 (전삼각근) 이차적으로는 옆쪽 삼각근, 삼두근, 승모근, 상부 대흉근입니다.',
      how:[
        '의자 높이를 조절하여 허벅지는 바닥과 평행하게 하고 머리는 벤치 가장 윗부분에 닿을 정도로 충분히 낮아야 하며 양측 손의 그립을 연결한 가상의 선이 어깨의 가장 윗부분이나 목덜미 부위보다 낮으면 안됩니다.',
        '신체 5부위(머리,어깨등,엉덩이,양측발) 접촉자세가 유지되어야 합니다.',
        '핸들을 닫힌 회내그립(closed pronated grip) 으로 잡습니다.',
        '핸들을 위로 올리면서 운동을 시작합니다.',
        '손목은 견고히 유지 되어야 하고 양측 아래팔(팔꿈치-손목부위)는 서로 평행하게 유지되어야 하며팔꿈치가 완전히 펴질 때까지 올리지만 관절을 lock시키면 안됩니다.',
        '올리는 동안 신체 5부위 자세를 유지해야 하며 등을 아치모양으로 만들거나 힙을 들어올리거나 일어서려는 것처럼 종아리를 위로 밀거나 고개를 뒤로 경사지게 하면 안됩니다. (어깨의 힘이 아닌 다른 부위의 동작을 통해 들어올리려는 시도들입니다.)',
        '핸들을 시작자세로 힘을 주면서 서서히 내립니다. 이 때 몸통을 앞으로 구부리면 안되며 신체5부위 자세를 유지하고 있어야 합니다.'
      ],
      caution:'숄더 프레스시 바를 얼굴 앞쪽이 아니라 뒷쪽으로 내리는 프레스(back presses 혹은 비하인드넥 숄더프레스(behind neck shoulder press))는 어깨 손상위험이 더 높습니다.\n회전근개의 운동은 회전근개의 충돌을 최소화하는 안전한 범위내에서 시행되어야 합니다.'
    }),
    imageLink: 'https://gif.helltabus.com/14541103/14541103-Lever-Seated-Shoulder-Press_Shoulders_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '이두컬',
    priority: 1,
    part: 'BICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'덤벨을 들고 팔을 굽히는 운동입니다. 선 자세와 앉은 자세(벤치, 짐볼)에서 운동이 가능하며, 그립을 잡는 방향에 따라 발현되는 근육이 달라지며, 양팔을 동시에 운동하거나 한 팔씩 번갈아가며 운동을 할 수도 있습니다.',
      where:'주 타격부위는 이두근이며 보조로 삼각근 전면과 전완근이 쓰입니다. 바벨 컬이 사이즈를 키우는데 더 유리한 운동이라면 덤벨 컬은 양쪽 이두근의 균형잡힌 발달과 높은 범용성의 장점이 있습니다. ',
      how:[
        '벤치에 앉아 다리는 골반 너비만큼 벌린 후 양손으로 덤벨을 잡고, 손바닥이 앞을 향하도록 합니다.',
        '팔꿈치를 옆구리에 고정시키고 덤벨을 들어올린다.들어올리는 마지막 지점에서 손목이 바깥쪽을 향하도록 합니다.',
        '천천히 이두근의 저항을 느끼며 덤벨을 내립니다.'
      ],
      caution:'팔꿈치가 앞으로 나가지 않도록 고정시킵니다.\n덤벨이 몸 바깥쪽으로 벗어나지 않도록 합니다.'
    }),
    imageLink: 'https://gif.helltabus.com/02941301/02941301-Dumbbell-Biceps-Curl_Upper-Arms_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '해머컬',
    priority: 2,
    part: 'BICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'이두근을 발달시키는 운동의 하나로 양쪽 손바닥이 마주 보도록 똑바로 선 상태로 그대로 덤벨을 어깨 쪽으로 들어 올리며 운동을 진행합니다. Hammer 해머는 망치를 뜻하며 망치를 두드릴 때의 모양을 말하고 Curl은 ‘들어올리다, 말아 올리다’라는 뜻을 가지고 있습니다. 쉽게 말하면 해머컬은 양손을 마주보게 하여 덤벨을 들어올린다는 뜻입니다.',
      where:'앞팔의 근육인 전완근과 이두근이 자극되며 이곳이 발달됩니다. 이두는 바깥쪽 근육인 장두와 뽀빠이자세를 취하면 힘줬을 때 나오는 알통인 단두로 나뉘는데 이중에서도 해머컬을 장두의 발달에 뛰어난 효과가 있는 운동입니다. 특히 이두근의 봉우리 발달에 좋은 운동이라고도 하는데 이두와 삼두 사이 쪽에 위치하는 근육을 발달시켜 이두근을 바깥쪽으로 밀어내 봉우리 형성에 큰 도움을 줍니다.',
      how:[
        '먼저 양손바닥을 마주 보게 하여 덤벨을 잡습니다. ',
        '팔꿈치를 옆구리에 붙인 뒤, 덤벨을 말아 올립니다. ',
        '천천히 원래 위치로 돌아갑니다. ',
        '횟수에 따라 반복해주시면 됩니다.'
      ],
      caution:'양 손바닥을 마주보게 하여 덤벨을 잡고 선 후 그 상태에서 그대로 팔을 말아 올려 줍니다. 이 때 중요한 포인트는 팔 운동시 포인트가 있는데 팔꿈치를 고정시켜야 합니다. 팔을 올리고 내릴때 팔꿈치가 움직이지 않고 고정이 되게 옆구리에 붙인 후 운동을 합니다. 팔 앞부분인 이두에 힘이 들어가는 것을 느끼면서 팔을 올릴때는 숨을 들이마시고 내릴때는 숨을 내쉬시면서 동작을 해줍니다. 처음부터 빠르게 하지 마시고 천천히 운동부위와 동작에 집중을 하시면서 운동을 하셔야 합니다. 팔을 올릴 때의 속도보다 내릴때의 속도를 천천히 하여 최대한 집중하셔서 하는 것이 좋습니다.'
    }),
    imageLink: 'https://gif.helltabus.com/03131301/03131301-Dumbbell-Hammer-Curl_Forearm_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '삼두 익스텐션',
    priority: 1,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 4,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'의자에 앉아 덤벨을 머리 뒤로 내렸다가 머리 위로 올리는, 삼두를 자극하는 운동입니다.',
      where:'삼두 익스텐션을 통해 자극되는 근육은 일차적으로 삼두근이며 2차 근육은 삼각근과 전완근입니다.',
      how:[
        '똑바로 앉아서 양손에 덤벨을 받칩니다. 양 손바닥에 50대 50으로 덤벨의 중량을 나누어 올려 중심을 잡아주시면 됩니다. ',
        '팔꿈치를 굽혀 덤벨이 머리 뒤로 내려오게 하신 후 팔꿈치를 최대한 펴주시면서 상완삼두근에 수축과 이완을 느낍니다.',
        '덤벨을 머리 뒤쪽으로 내릴때 팔꿈치가 너무 많이 벌어지지 않도록 주의하시는 것이 좋지만 어깨관절에 피로나 통증을 느낀다면 팔꿈치를 조금 벌려서 트레이닝 하는 것이 좋습니다.',
        '삼두 익스텐션은 팔꿈치만 사용하는 단순관절 운동으로 운동중에 어깨관절을 사용하지 않도록 주의하시는 것이 좋습니다.',
        '이 운동은 E-Z바를 이용할 수도 있습니다. 바벨을 이용하여 운동을 할때는 그립의 너비에 따라 삼두근의 운동자극 부위가 조금씩 틀려질 수 있습니다. 넓은 그립으로 트레이닝을 할 경우 삼두근의 장두에 조금 더 많은 자극이 올 것이며, 좁은 그립으로 트레이닝하면 삼두근의 외축에 조금 더 많은 자극이 옵니다.'
      ],
      caution:'익스텐션은 영어로 확장이라는 뜻으로 삼두를 확장시키는 운동입니다. 삼두 익스텐션의 장점은 운동 시작자세가 삼두근이 스트레칭 된 자세에서 시작하기 때문에 삼두근에 조금 더 많은 자극을 느끼게 할 수 있습니다. 하지만 어깨 통증이 있는 사람들은 가벼운 중량이나 팔을 머리 위로 올려서 시작하는 삼두근 운동을 피하시는 것이 좋습니다.'
    }),
    imageLink: 'https://gif.helltabus.com/21881301/21881301-Dumbbell-Seated-Triceps-Extension_Upper-Arms_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 킥백',
    priority: 2,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'덤벨 킥백은 삼두근 운동으로 아령과 의자만 있으면 집에서도 가능합니다. 보통 한쪽씩 실시하는 원암 형태가 기본이며, 고립운동으로 수축에 집중하는게 중요합니다.',
      where:'삼두중에서도 바깥 쪽에 특히 효과적인 운동입니다. 기본적으로는 삼두근을 골고루 발달시켜주며 자세, 수축을 바르게 실시한다면 다른 근육 부위의 사용을 최소화하고 정확히 삼두에만 집중할수 있는 장점이 있습니다.',
      how:[
        '한쪽 팔과 다리만 의자에 엎드린 자세를 취하며 굽혀서 받쳐 줍니다.',
        '윗팔-팔꿈치 윗 부위는 상체 몸통과 같은 방향에 고정을 시킵니다.',
        '몸통과 팔이 너무 떨어지거나 흔들리지 않도록 가까이 붙여서 고정합니다.',
        '몸통과 팔이 너무 떨어지거나 흔들리지 않도록 가까이 붙여서 고정합니다.'
      ],
      caution:'삼두근을 자극할 때는 팔을 쥐어짠다는 느낌으로 운동을 해줘야 합니다.\n가장 자극을 많이 받는 순간은 최대 수축지점 즉, 팔을 올리고 2초 정도 머무르는 상황에서 가장 많은 자극이 갑니다. 이때 힘들다고 팔이 추욱 떨어지지 않도록 잘 잡아 버텨줘야 합니다.'
    }),
    imageLink: 'https://gif.helltabus.com/03331301/03331301-Dumbbell-Kickback_Upper-Arms_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '케이블 푸쉬다운',
    priority: 3,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 0,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what:'케이블 머신을 이용하여 삼두근을 기를 수 있는 운동입니다.\n케이블 푸시다운은 `트라이셉스 푸시다운 또는 케입르 프레스 다운`이라고 불리기도 합니다.',
      where:'케이블 푸시다운은 삼두근 중에서도 장두와 외측두를 집중적으로 운동 할 수 있는 운동입니다.',
      how:[
        '상체를 살짝 숙인 상태로 자세를 잡습니다.(그립은 팔꿈치가 몸에 편하게 붙을 정도로 잡습니다.)',
        '어깨와 팔꿈치를 수직으로 만들어 주고, 팔꿈치를 앞뒤로 움직이면 안됩니다.',
        '전완근이 바득과 평행이 되도록 만들어주고, 아래로 천천히 내립니다.(팔꿈치는 최대로 펴주고, 제대로 안 펴지는 경우에는 무게가 높은거니 80% 수준으로 무게를 조정합니다.)',
        '천천히 팔을 들어올려 이완시킵니다.',
        '위의 동작들을 반복합니다.'
      ],
      caution:'상체를 너무 숙이거나 세우지 않습니다.\n바를 내렸을 때, 몸에 닿아 진행 방향을 막지 않도록 하고, 손목이 꺾이지 않도록 합니다.\n팔꿈치가 앞뒤로 움직이지 않도록, 옆구리에 붙여 고정하고 어깨가 개입 되지 않도록 합니다.'
    }),
    imageLink: 'https://gif.helltabus.com/02411301/02411301-Cable-Triceps-Pushdown-(V-bar-attachment)_Upper-Arms_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
];
