export const ExerciseSeed = [
  {
    name: '스쿼트',
    priority: 1,
    part: 'LOWER',
    baseCount: 15,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: JSON.stringify({
      what: 'Squat는 쪼그리고 앉다는 뜻으로 데드리프트, 벤치프레스와 더불어 웨이트 트레이닝의 3대 운동 중 하나입니다.\n특히 하체 운동에서는 절대 빠지면 안 되는 운동입니다.\n바벨 또는 덤벨을 들고 혹은 맨몸으로 무릎 관절을 굽혀다 펴는 행동을 반복함으로써 하반신의 근육을 성장시키는 운동입니다.',
      where: '대퇴사두근, 둔근, 척주기립근, 복부 근육, 대퇴근 후면 근육이 집중적으로 운동됩니다.\n위 근육들이 스쿼트 자극 부위라고 생각하고 운동해 주셔야 합니다.',
      how: [
      '앉았다 일어나는 동작을 기본으로 하는데 어깨너비로 발을 벌리고 서서 발가락이 전면을 향하도록 선 후, 허리는 곧게 펴고, 상체도 최대한 꼿꼿하게 펴는 것이 좋습니다.',
      '무릎의 위치를 신경 쓰기보다는 의자에 앉는다는 느낌으로 자연스럽게 엉덩이를 낮추면 됩니다.\n개인마다 신체 비율이 다르기 때문에 스쿼트를 처음 시작할 때는 누군가 봐주거나 거울을 통해 자신의 모습을 지켜보는 것이 좋습니다.',
      '스쿼트에서 가장 중요한 것은 엉덩이를 낮췄다가 일어나는 동작에서 반동으로 움직이는 것이 아니라 복부와 엉덩이의 힘으로 일어나야 합니다.\n반동을 주며 횟수를 많이 하는 것은 운동 효과에 도움이 되지 않으며, 천천히 바른 자세로 제대로 하는 것이 중요합니다.',
      ],
      caution: '스쿼트는 분명히 프리 웨이트 중에서 최고의 운동효과를 낼 수 있는 운동입니다.\n하지만 최고의 프리 웨이트답게 생각보다 높은 난이도를 자랑하는 운동입니다.\n지도자들이나 트레이너들도 조금 더 깊이 있게 들어가면 스쿼트에 관해서 쩔쩔매는 것이 사실입니다.\n또한 인터넷이나 책으로만 접하거나 제대로 된 교육을 받지 않은 많은 사람들이 잘못된 자세로 스쿼트를 시행하는 경우를 볼 수 있습니다.\n잘못된 자세로 시행되는 스쿼트는 무릎-허리와 같은 회복 불가능의 퇴행성 질환을 유발하며 어깨와 손목에도 심각한 부상을 유발하기도 합니다.\n무조건 달려가서 무거운 중량으로 하기보다는 반드시 정확한 자세를 습득 후에 시행하기 바랍니다.',
      })
      ,
    imageLink: 'https://gif.helltabus.com/17601301/17601301-Dumbbell-Goblet-Squat_Thighs-FIX_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '런지',
    priority: 2,
    part: 'LOWER',
    baseCount: 15,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03361301/03361301-Dumbbell-Lunge_Hips_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레그 프레스',
    priority: 3,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/07391301/07391301-Sled-45-370-Leg-Press_Hips_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '라잉 레그 컬',
    priority: 4,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/05861301/05861301-Lever-Lying-Leg-Curl_Thighs_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레그익스텐션',
    priority: 5,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/05851301/05851301-Lever-Leg-Extension_Thighs_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 벤트 오버 로우',
    priority: 1,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/02931301/02931301-Dumbbell-Bent-Over-Row_Back-FIX_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 암 풀오버',
    priority: 2,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 4,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/04331301/04331301-Dumbbell-Straight-Arm-Pullover_Chest-FIX_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '렛풀다운',
    priority: 3,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/01971301/01971301-Cable-Pulldown-(pro-lat-bar)_Back_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '시티드로우',
    priority: 4,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/02391301/02391301-Cable-Straight-Back-Seated-Row_Back_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '백익스텐션',
    priority: 5,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/08771301/08771301-45-degree-hyperextension-(arms-in-front-of-chest)_Back_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 벤치프레스',
    priority: 1,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/02891301/02891301-Dumbbell-Bench-Press_Chest_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  }, {
    name: '덤벨 플라이',
    priority: 2,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03081301/03081301-Dumbbell-Fly_Chest-FIX_1080.gif',

    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 인크라인 벤치프레스',
    priority: 3,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03141301/03141301-Dumbbell-Incline-Bench-Press_Chest_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 체스트 프레스',
    priority: 4,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/05771301/05771301-Lever-Chest-Press_Chest_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 시티드 플라이',
    priority: 5,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/05961301/05961301-Lever-Seated-Fly_Chest_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레터럴 레이즈',
    priority: 1,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03341301/03341301-Dumbbell-Lateral-Raise_shoulder-AFIX_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '프론트 레이즈',
    priority: 2,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03101301/03101301-Dumbbell-Front-Raise_Shoulders_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '리어 레터럴 레이즈',
    priority: 3,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03801301/03801301-Dumbbell-Rear-Lateral-Raise_Shoulders_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '아놀드 프레스',
    priority: 4,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/21371301/21371301-Dumbbell-Arnold-Press_Shoulders_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 숄더 프레스',
    priority: 5,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/14541103/14541103-Lever-Seated-Shoulder-Press_Shoulders_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '이두컬',
    priority: 1,
    part: 'BICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/02941301/02941301-Dumbbell-Biceps-Curl_Upper-Arms_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '해머컬',
    priority: 2,
    part: 'BICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03131301/03131301-Dumbbell-Hammer-Curl_Forearm_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '삼두 익스텐션',
    priority: 1,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 4,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/21881301/21881301-Dumbbell-Seated-Triceps-Extension_Upper-Arms_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 킥백',
    priority: 2,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/03331301/03331301-Dumbbell-Kickback_Upper-Arms_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '케이블 푸쉬다운',
    priority: 3,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 0,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    description: "",
    imageLink: 'https://gif.helltabus.com/02411301/02411301-Cable-Triceps-Pushdown-(V-bar-attachment)_Upper-Arms_1080.gif',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
];
