export const ExerciseSeed = [
  {
    name: '스쿼트',
    priority: 1,
    part: 'LOWER',
    baseCount: 15,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/3795-dumbbell-goblet-squat.html#/47-stype_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '런지',
    priority: 2,
    part: 'LOWER',
    baseCount: 15,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1837-dumbbell-lunge.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레그 프레스',
    priority: 3,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/2222-sled-45-leg-press.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '라잉 레그 컬',
    priority: 4,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/2083-lever-lying-leg-curl.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레그익스텐션',
    priority: 5,
    part: 'LOWER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/2082-lever-leg-extension.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 벤트 오버 로우',
    priority: 1,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1786-dumbbell-bent-over-row.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 암 풀오버',
    priority: 2,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 4,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1934-dumbbell-straight-arm-pullover.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '렛풀다운',
    priority: 3,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1690-cable-pulldown-pro-lat-bar.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '시티드로우',
    priority: 4,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1732-cable-straight-back-seated-row.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '백익스텐션',
    priority: 5,
    part: 'BACK',
    baseCount: 10,
    setCount: 3,
    startWeight: 0,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/2355-45-degree-hyperextension-arms-in-front-of-chest.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 벤치프레스',
    priority: 1,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1782-dumbbell-bench-press.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },{
    name: '덤벨 플라이',
    priority: 2,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1801-dumbbell-fly.html#/47-style_type-basic_grey',

    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 인크라인 벤치프레스',
    priority: 3,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1807-dumbbell-incline-bench-press.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 체스트 프레스',
    priority: 4,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/2074-lever-chest-press.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 시티드 플라이',
    priority: 5,
    part: 'CHEST',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/2093-lever-seated-fly.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레터럴 레이즈',
    priority: 1,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1835-dumbbell-lateral-raise.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '프론트 레이즈',
    priority: 2,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1803-dumbbell-front-raise.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '리어 레터럴 레이즈',
    priority: 3,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1881-dumbbell-rear-lateral-raise.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '아놀드 프레스',
    priority: 4,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/4176-dumbbell-arnold-press.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '레버 숄더 프레스',
    priority: 5,
    part: 'SHOULDER',
    baseCount: 10,
    setCount: 3,
    startWeight: 5,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/2927-lever-seated-shoulder-press.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '이두컬',
    priority: 1,
    part: 'BICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1787-dumbbell-biceps-curl.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '해머컬',
    priority: 2,
    part: 'BICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1806-dumbbell-hammer-curl.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '삼두 익스텐션',
    priority: 1,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 4,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/4223-dumbbell-seated-triceps-extension.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '덤벨 킥백',
    priority: 2,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 1,
    changeWeight: 1,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1834-dumbbell-kickback.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
  {
    name: '케이블 푸쉬다운',
    priority: 3,
    part: 'TRICEPS',
    baseCount: 10,
    setCount: 3,
    startWeight: 0,
    changeWeight: 5,
    setBreakTime: 120,
    breakTime: 600,
    imageLink: 'https://www.gymvisual.com/animated-gifs/1734-cable-triceps-pushdown-v-bar-attachment.html#/47-style_type-basic_grey',
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
    deletedAt: null,
  },
];

module.exports = ExerciseSeed;
